export const metadata = { title: "Medical Disclaimer" };

export default function Page() {
  return (
    <>
      <h1>Medical Disclaimer</h1>
      <p>Last updated: {new Date().getFullYear()}</p>
      <p>
        FitTrack provides <strong>general fitness and nutrition information only</strong>. It is not
        medical advice, diagnosis, or treatment, and it is not a substitute for the advice of a
        qualified healthcare professional.
      </p>
      <h2>Always consult a professional</h2>
      <p>
        The calorie, macronutrient, hydration, and exercise recommendations generated by FitTrack are
        estimates based on population-level formulas. They may not be appropriate for you. Consult
        your doctor or a registered dietitian before starting any diet or exercise program,
        especially if you have a medical condition, are pregnant or postpartum, are under 18, are
        recovering from injury, or have a history of disordered eating.
      </p>
      <h2>Conditions requiring clearance</h2>
      <p>
        If you declared diabetes, high blood pressure, a heart condition, or pregnancy, you must
        obtain clearance from your physician before following any plan. Stop any activity immediately
        if you feel pain, dizziness, or distress, and seek medical attention.
      </p>
      <h2>No liability</h2>
      <p>
        You use FitTrack at your own risk. To the fullest extent permitted by law, FitTrack and its
        creators are not liable for any injury, loss, or damage arising from use of the app.
      </p>
    </>
  );
}
